FROM python:3.11-slim-trixie

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        ffmpeg \
        git \
        procps \
        gcc

RUN pip3 install -U pip
RUN pip3 install --no-cache --upgrade pip setuptools

COPY requirements.txt .

RUN pip3 install --default-timeout=900 -r requirements.txt

RUN git clone https://github.com/Rapptz/discord.py discord.py
WORKDIR /discord.py
RUN pip3 install -U .[voice]

WORKDIR /
RUN rm -rf discord.py

WORKDIR /app
COPY main.py .
COPY utils.py .
COPY database.py .
COPY populate_db.py .
COPY populate_anyllm.py .
COPY embed_file_anyllm.py .
COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

CMD ["./entrypoint.sh"]
