services:
  discord-llm-bot-rust:
    pull_policy: build
    build:
      context: ./bot
      dockerfile: Dockerfile
      network: host
    container_name: discord-bot-rust
    network_mode: host
    volumes:
      - ".env:/app/.env"
      - "./config:/app/config"
      - "/tmp/discord-llm-bot:/tmp/discord-llm-bot"
      - "./audios:/app/audios"
    image: "blastbeng/discord-llm-bot-rust:1.0.0"
    restart: no
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f discord-llm-bot || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
