services:
  discord-llm-bot-go:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: discord-bot-go
    network_mode: host
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GUILD_ID=${GUILD_ID}
      - ADMIN_ID=${ADMIN_ID}
      - LOG_LEVEL=info
      - TMP_DIR=/tmp/discord-llm-bot
    volumes:
      - ".env:/app/.env"
      - "./config:/app/config"
      - "/tmp/discord-llm-bot:/tmp/discord-llm-bot"
    restart: unless-stopped
