//! Automatic voice-channel behaviour for the Discord bot.
//!
//! This module implements the "auto-join" feature:
//! - When a user joins a voice channel the bot has permission for, the bot
//!   joins it (if it's disconnected or alone in its current channel) and
//!   switches to the user's channel otherwise.
//! - When a user joins the channel the bot is already in, the bot speaks a
//!   short, humorous welcome phrase (generated by the LLM using the database
//!   sentences as style context, or falling back to a random database sentence),
//!   delivered with a randomly-chosen audio effect (or none).
//! - When the bot is left alone in a voice channel for a configurable timeout,
//!   it disconnects.
//!
//! Everything is gated behind `AUTO_JOIN_VOICE=true` so the feature is opt-in.

use crate::{database, llm, tts, Data};
use poise::serenity_prelude as serenity;
use rand::seq::SliceRandom;
use std::collections::HashMap;
use std::time::{Duration, Instant};

/// Master switch: whether auto-join/welcome behaviour is enabled at all.
pub fn config_enabled() -> bool {
    std::env::var("AUTO_JOIN_VOICE")
        .unwrap_or_else(|_| "false".to_string())
        .to_lowercase()
        == "true"
}

/// Whether to speak a welcome phrase when auto-joining. Defaults to true.
pub fn config_welcome() -> bool {
    std::env::var("AUTO_JOIN_WELCOME")
        .map(|v| v.to_lowercase() == "true")
        .unwrap_or(true)
}

/// Whether to speak a goodbye/insult phrase when a user leaves the bot's
/// voice channel. Defaults to true.
pub fn config_goodbye() -> bool {
    std::env::var("AUTO_JOIN_GOODBYE")
        .map(|v| v.to_lowercase() == "true")
        .unwrap_or(true)
}

/// How many seconds the bot may remain alone in a voice channel before
/// disconnecting. Defaults to 120 (2 minutes).
pub fn config_idle_disconnect_secs() -> u64 {
    std::env::var("AUTO_JOIN_IDLE_DISCONNECT_SECS")
        .ok()
        .and_then(|v| v.trim().parse().ok())
        .unwrap_or(120)
}

/// Called from the event handler on every voice state update.
pub async fn handle_voice_state_update(
    ctx: &serenity::Context,
    data: &Data,
    old: Option<&serenity::VoiceState>,
    new: &serenity::VoiceState,
) {
    // Ignore the bot's own voice state changes — this also avoids an infinite
    // loop where the bot moving triggers another event for itself.
    if new.user_id == ctx.cache.current_user().id {
        return;
    }

    let Some(guild_id) = new.guild_id else { return };

    let old_channel = old.and_then(|o| o.channel_id);
    let new_channel = new.channel_id;

    // Determine what happened: join, leave, or move (leave+join in same event)
    let left_channel = old_channel.filter(|c| new_channel != Some(*c));
    let joined_channel = new_channel.filter(|c| old_channel != Some(*c));

    // ── USER JOINED A CHANNEL ──────────────────────────────────────────────
    if let Some(channel_id) = joined_channel {
        // Best-effort display name for the welcome phrase.
        let user_name = new
            .user_id
            .to_user(ctx.http.clone())
            .await
            .map(|u| u.name)
            .unwrap_or_else(|_| "qualcuno".to_string());

        let bot_channel = current_bot_channel(ctx, guild_id).await;

        match bot_channel {
            Some(c) if c == channel_id => {
                // User joined the channel the bot is already in — welcome them.
                log::info!("auto_join: user {} joined bot's channel {}, welcoming", user_name, channel_id);
                speak_welcome(ctx, data, guild_id, channel_id, &user_name).await;
            }
            Some(c) => {
                // Bot is in a different channel. Only follow the user if the bot is
                // otherwise alone — never abandon people currently in the channel.
                if count_humans(ctx, guild_id, c) == 0 && has_permission(ctx, guild_id, channel_id).await {
                    log::info!("auto_join: bot alone, switching from {} to {}", c, channel_id);
                    switch_to(ctx, guild_id, c, channel_id).await;
                    speak_welcome(ctx, data, guild_id, channel_id, &user_name).await;
                }
            }
            None => {
                // Bot disconnected — connect to the user's channel and greet them.
                if has_permission(ctx, guild_id, channel_id).await {
                    log::info!("auto_join: bot disconnected, joining {} for user {}", channel_id, user_name);
                    join_channel(ctx, guild_id, channel_id).await;
                    speak_welcome(ctx, data, guild_id, channel_id, &user_name).await;
                }
            }
        }
    }

    // ── USER LEFT A CHANNEL ────────────────────────────────────────────────
    if let Some(left_channel) = left_channel {
        // Only insult if the user left the bot's current channel and goodbye is enabled.
        let bot_channel = current_bot_channel(ctx, guild_id).await;
        if bot_channel == Some(left_channel) && data.auto_join_goodbye {
            // Fetch the user's name before they fully disconnect from the cache.
            let user_name = new
                .user_id
                .to_user(ctx.http.clone())
                .await
                .map(|u| u.name)
                .unwrap_or_else(|_| "qualcuno".to_string());

            log::info!("auto_join: user {} left bot's channel {}, insulting", user_name, left_channel);
            speak_goodbye(ctx, data, guild_id, left_channel, &user_name).await;
        }
    }
}

/// Background loop that disconnects the bot from voice channels once it has
/// been alone for `AUTO_JOIN_IDLE_DISCONNECT_SECS`.
pub async fn idle_disconnect_loop(ctx: serenity::Context) {
    let timeout = Duration::from_secs(config_idle_disconnect_secs());
    // When the bot first became alone in each guild (keyed by guild id).
    let mut alone_since: HashMap<u64, Instant> = HashMap::new();

    let mut ticker = tokio::time::interval(Duration::from_secs(10));
    log::info!("auto_join: idle-disconnect loop started (timeout {}s)", timeout.as_secs());

    loop {
        ticker.tick().await;

        let Some(manager) = songbird::get(&ctx).await else { continue };
        // Songbird has its own GuildId type; convert to serenity's for the cache.
        let guild_ids: Vec<serenity::GuildId> = manager
            .iter()
            .map(|(id, _)| serenity::GuildId::new(id.0.get()))
            .collect();

        for guild_id in guild_ids {
            let Some(handler) = manager.get(guild_id) else { continue };

            // Current channel (songbird ChannelId → serenity ChannelId for the cache).
            let current = handler
                .lock()
                .await
                .current_channel()
                .map(|c| serenity::ChannelId::new(c.0.get()));
            let alone = match current {
                Some(ch) => count_humans(&ctx, guild_id, ch) == 0,
                None => true,
            };

            if alone {
                let entry = alone_since.entry(guild_id.get()).or_insert_with(Instant::now);
                if entry.elapsed() >= timeout {
                    let mut h = handler.lock().await;
                    let _ = h.leave().await;
                    alone_since.remove(&guild_id.get());
                    log::info!("auto_join: disconnected from guild {} after {}s alone", guild_id, timeout.as_secs());
                }
            } else {
                alone_since.remove(&guild_id.get());
            }
        }
    }
}

/// Periodic scanner that finds the most-populated voice channel in each guild
/// and joins it if the bot is disconnected and there are people talking.
/// This catches the case where the bot was offline or restarted while
/// people were already in a voice channel.
pub async fn channel_scanner_loop(ctx: serenity::Context) {
    let http = ctx.http.clone();
    let cache = ctx.clone();
    let mut ticker = tokio::time::interval(Duration::from_secs(30));
    log::info!("auto_join: channel scanner loop started");

    loop {
        ticker.tick().await;

        // Get the bot's user ID once per tick (needed for filtering)
        let bot_user_id = cache.cache.current_user().id;

        // Iterate over all cached guilds
        for guild_id in cache.cache.guilds() {
            // Step 1: collect channel/human info synchronously and drop the cache lock.
            let voice_channel_counts: Vec<_> = {
                let Some(guild_data) = cache.cache.guild(guild_id) else { continue };
                guild_data
                    .channels
                    .values()
                    .filter(|ch| matches!(ch.kind, serenity::ChannelType::Voice))
                    .filter_map(|ch| {
                        let human_count = guild_data
                            .voice_states
                            .values()
                            .filter(|vs| {
                                vs.channel_id == Some(ch.id) && vs.user_id != bot_user_id
                            })
                            .count();
                        if human_count > 0 {
                            Some((ch.id, human_count))
                        } else {
                            None
                        }
                    })
                    .collect()
            };

            // Step 2: now safe to await — no cache lock held.
            let Some(manager) = songbird::get(&cache).await else { continue };
            if manager.get(guild_id).is_some() {
                continue;
            }

            // Find the most-populated channel
            let best = voice_channel_counts
                .into_iter()
                .max_by_key(|(_, count)| *count);

            if let Some((channel_id, human_count)) = best {
                // Check permissions before joining
                match channel_id.to_channel(&http).await {
                    Ok(serenity::Channel::Guild(gc)) => {
                        #[allow(deprecated)]
                        match gc.permissions_for_user(&cache.cache, bot_user_id) {
                            Ok(p) if p.connect() && p.speak() => {
                                log::info!("auto_join: scanner found {} humans in channel {}, joining...", human_count, channel_id);
                                let _ = manager.join(guild_id, channel_id).await;
                                log::info!("auto_join: scanner joined channel {}", channel_id);
                            }
                            Ok(_) => {
                                log::debug!("auto_join: scanner skipped channel {} (no permission)", channel_id);
                            }
                            Err(e) => {
                                log::warn!("auto_join: scanner permissions_for_user failed for {}: {}", channel_id, e);
                            }
                        }
                    }
                    Ok(_) => {}
                    Err(e) => {
                        log::warn!("auto_join: scanner failed to fetch channel {}: {}", channel_id, e);
                    }
                }
            }
        }
    }
}

/// The channel the bot is currently connected to in a guild, if any.
async fn current_bot_channel(
    ctx: &serenity::Context,
    guild_id: serenity::GuildId,
) -> Option<serenity::ChannelId> {
    let manager = songbird::get(ctx).await?;
    let handler = manager.get(guild_id)?;
    let guard = handler.lock().await;
    // songbird::ChannelId → serenity::ChannelId (uses the underlying u64).
    match guard.current_channel() {
        Some(c) => Some(serenity::ChannelId::new(c.0.get())),
        None => None,
    }
}

/// Number of non-bot voice-state users present in a channel.
fn count_humans(ctx: &serenity::Context, guild_id: serenity::GuildId, channel_id: serenity::ChannelId) -> usize {
    let Some(guild) = ctx.cache.guild(guild_id) else { return 0 };
    guild
        .voice_states
        .values()
        .filter(|vs| vs.channel_id == Some(channel_id) && vs.user_id != ctx.cache.current_user().id)
        .count()
}

/// Whether the bot has connect + speak permission in the given channel.
async fn has_permission(
    ctx: &serenity::Context,
    guild_id: serenity::GuildId,
    channel_id: serenity::ChannelId,
) -> bool {
    let Ok(channel) = channel_id.to_channel(ctx).await else {
        log::warn!("auto_join: has_permission: failed to fetch channel {} (not found or no access)", channel_id);
        return false;
    };
    if let serenity::Channel::Guild(gc) = channel {
        #[allow(deprecated)]
        if let Ok(p) = gc.permissions_for_user(&ctx.cache, ctx.cache.current_user().id) {
            let can_connect = p.connect();
            let can_speak = p.speak();
            let can_view = p.view_channel();
            log::debug!("auto_join: has_permission channel {} bot perms: view={} connect={} speak={}", channel_id, can_view, can_connect, can_speak);
            return can_connect && can_speak;
        } else {
            log::warn!("auto_join: has_permission: permissions_for_user failed for channel {}", channel_id);
        }
    }
    false
}

/// Join a voice channel (assumes the bot is not already there).
async fn join_channel(
    ctx: &serenity::Context,
    guild_id: serenity::GuildId,
    channel_id: serenity::ChannelId,
) {
    if let Some(manager) = songbird::get(ctx).await {
        let _ = manager.join(guild_id, channel_id).await;
    }
}

/// Leave the current channel and join a new one.
async fn switch_to(
    ctx: &serenity::Context,
    guild_id: serenity::GuildId,
    _current: serenity::ChannelId,
    target: serenity::ChannelId,
) {
    if let Some(manager) = songbird::get(ctx).await {
        if let Some(handler) = manager.get(guild_id) {
            let mut h = handler.lock().await;
            let _ = h.leave().await;
            drop(h);
            tokio::time::sleep(Duration::from_millis(500)).await;
        }
        let _ = manager.join(guild_id, target).await;
    }
}

/// Speak a welcome phrase in the given channel, throttled so rapid successive
/// joins don't trigger an LLM call (and TTS) every time.
async fn speak_welcome(
    ctx: &serenity::Context,
    data: &Data,
    guild_id: serenity::GuildId,
    channel_id: serenity::ChannelId,
    user_name: &str,
) {
    // Throttle: at most one welcome per channel every 30 seconds.
    const COOLDOWN: Duration = Duration::from_secs(30);
    let now = Instant::now();
    {
        let mut last_welcome = data.last_welcome.lock().unwrap();
        if let Some(last) = last_welcome.get(&channel_id.get()) {
            if now.duration_since(*last) < COOLDOWN {
                return;
            }
        }
        last_welcome.insert(channel_id.get(), now);
    }

    let phrase = if data.auto_join_welcome {
        let db_sentences = database::select_all_sentence(&data.db_pool).await.unwrap_or_default();

        // Prefer the LLM-generated welcome. If the LLM is configured but
        // returns an error (including garbage/invalid responses), do NOT fall
        // back to a random DB sentence — silence is better than a wrong
        // message. Only fall back if the LLM is not configured at all.
        if llm::is_configured() {
            match llm::welcome(user_name, &db_sentences).await {
                Ok(p) => p,
                Err(e) => {
                    log::warn!("auto_join: welcome LLM error, skipping welcome: {}", e);
                    return;
                }
            }
        } else {
            // LLM not configured — fall back to a random database sentence.
            match db_sentences.choose(&mut rand::thread_rng()) {
                Some(s) => s.clone(),
                None => return,
            }
        }
    } else {
        // Welcoming speech disabled entirely — nothing to say.
        return;
    };

    // Welcome audio is always played without effects. The raw Google TTS bytes
    // are written directly to disk (no MP3 round-trip) so playback is reliable
    // and the welcome is always clear/intelligible.
    let effect = "none";

    let tts_result = match tts::get_or_generate_tts_with_effect(&phrase, "Google", effect).await {
        Ok(r) => r,
        Err(e) => {
            log::warn!("auto_join: TTS failed for welcome: {}", e);
            return;
        }
    };

    if let Some(manager) = songbird::get(ctx).await {
        if let Some(handler) = manager.get(guild_id) {
            let mut h = handler.lock().await;
            if h.current_channel().is_some() {
                // Play the welcome, applying the user-set volume so it matches
                // /speak and other commands (which go through play_with_volume).
                let source = songbird::input::File::new(tts_result.file_path.clone());
                let track = h.play_only(source.into());
                let vol = *data.volume.lock().unwrap();
                let _ = track.set_volume(vol);
                log::info!("auto_join: playing welcome for {} (effect: {}, volume: {}): {}", user_name, effect, vol, phrase);
            }
        }
    }
}

/// Speak a short, insulting goodbye phrase when a user leaves the bot's voice
/// channel. Throttled per-channel so rapid successive leaves don't spam the
/// LLM. Mirrors `speak_welcome` but biases the LLM towards cheeky insults.
async fn speak_goodbye(
    ctx: &serenity::Context,
    data: &Data,
    guild_id: serenity::GuildId,
    channel_id: serenity::ChannelId,
    user_name: &str,
) {
    // Throttle: at most one goodbye per channel every 30 seconds.
    const COOLDOWN: Duration = Duration::from_secs(30);
    let now = Instant::now();
    {
        let mut last_goodbye = data.last_goodbye.lock().unwrap();
        if let Some(last) = last_goodbye.get(&channel_id.get()) {
            if now.duration_since(*last) < COOLDOWN {
                return;
            }
        }
        last_goodbye.insert(channel_id.get(), now);
    }

    let db_sentences = database::select_all_sentence(&data.db_pool).await.unwrap_or_default();

    // Prefer LLM insult. If the LLM is configured but returns an error
    // (including garbage/invalid responses), do NOT fall back to a random
    // DB sentence — silence is better than a wrong message. Only fall back
    // if the LLM is not configured at all.
    let phrase = if llm::is_configured() {
        match llm::goodbye(user_name, &db_sentences).await {
            Ok(p) => p,
            Err(e) => {
                log::warn!("auto_join: goodbye LLM error, skipping goodbye: {}", e);
                return;
            }
        }
    } else {
        match db_sentences.choose(&mut rand::thread_rng()) {
            Some(s) => s.clone(),
            None => return,
        }
    };

    // Goodbye is always played without effects for clarity and reliability.
    let effect = "none";

    let tts_result = match tts::get_or_generate_tts_with_effect(&phrase, "Google", effect).await {
        Ok(r) => r,
        Err(e) => {
            log::warn!("auto_join: TTS failed for goodbye: {}", e);
            return;
        }
    };

    if let Some(manager) = songbird::get(ctx).await {
        if let Some(handler) = manager.get(guild_id) {
            let mut h = handler.lock().await;
            if h.current_channel().is_some() {
                let source = songbird::input::File::new(tts_result.file_path.clone());
                let track = h.play_only(source.into());
                let vol = *data.volume.lock().unwrap();
                let _ = track.set_volume(vol);
                log::info!("auto_join: playing goodbye for {} (volume: {}): {}", user_name, vol, phrase);
            }
        }
    }
}
