use std::env;

#[derive(Debug)]
pub struct Lang {
    pub join_success: String,
    pub join_success_to_self: String,
    pub join_error: String,
    pub leave_success: String,
    pub not_connected: String,
    pub stop_success: String,
    pub tts_error: String,
    pub tts_error_fakeyou: String,
    pub tts_error_google: String,
    pub playing: String,
    pub no_sentence: String,
    pub invalid_extension: String,
    pub audio_playback: String,
    pub admin_parent_server: String,
    pub admin_only: String,
    pub restarting: String,
    pub nickname_too_long: String,
    pub nickname_changed: String,
    pub unsupported_file: String,
    pub avatar_changed: String,
    pub spam_messages: Vec<String>,
    pub generating_audio: String,
    pub searching_random: String,
    pub discord_api_error: String,
    pub queue_overload: String,
    pub no_sentence_with_text: String,
    pub replaying_audio: String,
    pub guild_not_found: String,
    pub must_be_in_voice: String,
    pub no_speak_permission: String,
    pub fakeyou_warning: String,
    pub bot_not_ready: String,
    pub initializing_connection: String,
    pub invalid_voice: String,
    pub wrong_guild: String,
    pub disagio: String,
    pub user_no_permission: String,
    pub text_too_long: String,
}

impl Lang {
    pub fn new() -> Self {
        let lang = env::var("LANG").unwrap_or_else(|_| "ita".to_string());
        match lang.as_str() {
            "eng" => Self {
                join_success: "I'm joining the channel".to_string(),
                join_success_to_self: "I'm joining your channel, <@{}>".to_string(),
                join_error: "Error joining the channel".to_string(),
                leave_success: "I'm leaving the channel".to_string(),
                not_connected: "I'm not connected to any channel".to_string(),
                stop_success: "Stopping the bot".to_string(),
                tts_error: "Error generating audio, please try again in a moment.".to_string(),
                tts_error_fakeyou: "FakeYou is receiving too many requests, try selecting a different voice.".to_string(),
                tts_error_google: "Error generating audio, try selecting a different voice.".to_string(),
                playing: "Playing: **{}** with voice: {}".to_string(),
                no_sentence: "No sentence found".to_string(),
                invalid_extension: "The file extension is not valid.".to_string(),
                audio_playback: "Done! I'm starting the audio playback!".to_string(),
                admin_parent_server: "Only administrators can use this command in the parent server".to_string(),
                admin_only: "Only administrators can use this command".to_string(),
                restarting: "I'm restarting the bot.".to_string(),
                nickname_too_long: "My nickname cannot be longer than 32 characters".to_string(),
                nickname_changed: "You renamed me to \"{}\"".to_string(),
                unsupported_file: "This file type is not supported".to_string(),
                avatar_changed: "The image has been changed".to_string(),
                spam_messages: vec![
                    "Spam detected. <@{}> I'm watching you.".to_string(),
                    "Spam detected. <@{}> This doesn't make you a good person.".to_string(),
                    "Spam detected. <@{}> I'm stupid but not boring.".to_string(),
                    "Spam detected. <@{}> Take your time.".to_string(),
                    "Spam detected. <@{}> Keep calm.".to_string(),
                    "Spam detected. <@{}> Do you behave like this at home too?".to_string(),
                    "Spam detected. <@{}> Why are you so anxious?".to_string(),
                    "Spam detected. <@{}> I'm adding you to the blacklist.".to_string(),
                ],
                generating_audio: "I'm starting to generate audio for the sentence: **{}**{}".to_string(),
                searching_random: "I'm looking for a random sentence{}".to_string(),
                discord_api_error: "Discord API Error, please try again later".to_string(),
                queue_overload: "\n\nIf the server is overloaded, it might take a while\n*CPU: {:.1}% - RAM: {:.2}%*".to_string(),
                no_sentence_with_text: "No sentence found containing the text \"{}\"".to_string(),
                replaying_audio: "Replaying audio...".to_string(),
                guild_not_found: "Guild not found".to_string(),
                must_be_in_voice: "You must be in a voice channel to use this command".to_string(),
                no_speak_permission: "I don't have permission to speak or connect in this channel".to_string(),
                fakeyou_warning: "\n\nWARNING: FakeYou is receiving too many requests, audio generated using Google voice".to_string(),
                bot_not_ready: "The bot is not ready yet or another user is using a command.\nPlease try again later or use the /stop command".to_string(),
                initializing_connection: "Please try again later, I'm initializing the connection...".to_string(),
                invalid_voice: "Invalid voice selected.".to_string(),
                wrong_guild: "This bot can only be used in the parent server".to_string(),
                disagio: "Disagio.".to_string(),
                user_no_permission: "You don't have permission to use this command in this voice channel.".to_string(),
                text_too_long: "The text is too long (max 200 characters). Please shorten it and try again.".to_string(),
            },
            _ => Self {
                join_success: "Sto entrando nel canale".to_string(),
                join_success_to_self: "Sto entrando nel tuo canale, <@{}>".to_string(),
                join_error: "Errore nell'entrare nel canale".to_string(),
                leave_success: "Sto lasciando il canale".to_string(),
                not_connected: "Non sono connesso a nessun canale".to_string(),
                stop_success: "Interrompo il bot".to_string(),
                tts_error: "Errore nella generazione dell'audio, riprovare fra qualche istante.".to_string(),
                tts_error_fakeyou: "FakeYou sta ricevendo troppe richieste, prova a selezionare una voce diversa.".to_string(),
                tts_error_google: "Errore nella generazione dell'audio, prova a selezionare una voce diversa.".to_string(),
                playing: "Sto riproducendo: **{}** con voce: {}".to_string(),
                no_sentence: "Nessuna frase trovata".to_string(),
                invalid_extension: "L'estensione del file non è valida.".to_string(),
                audio_playback: "Fatto! Sto avviando la riproduzione dell'audio!".to_string(),
                admin_parent_server: "Solo gli amministratori possono utilizzare questo comando nel server padre".to_string(),
                admin_only: "Solo gli amministratori possono utilizzare questo comando".to_string(),
                restarting: "Sto riavviando il bot.".to_string(),
                nickname_too_long: "Il mio nickname non puó essere piú lungo di 32 caratteri".to_string(),
                nickname_changed: "Mi hai rinominato in \"{}\"".to_string(),
                unsupported_file: "Questo tipo di file non é supportato".to_string(),
                avatar_changed: "L'immagine é stata modificata".to_string(),
                spam_messages: vec![
                    "Spam detected. <@{}> Ti sto guardando.".to_string(),
                    "Spam detected. <@{}> Questo non ti rende una brava persona.".to_string(),
                    "Spam detected. <@{}> Sono stupido ma non noioso.".to_string(),
                    "Spam detected. <@{}> Prenditi il tuo tempo.".to_string(),
                    "Spam detected. <@{}> Mantieni la calma.".to_string(),
                    "Spam detected. <@{}> Anche a casa tua ti comporti cosí?".to_string(),
                    "Spam detected. <@{}> Perché sei cosí ansioso?".to_string(),
                    "Spam detected. <@{}> Ti aggiungo alla blacklist.".to_string(),
                ],
                generating_audio: "Inizio a generare l'audio per la frase: **{}**{}".to_string(),
                searching_random: "Sto cercando una frase casuale{}".to_string(),
                discord_api_error: "Discord API Error, per favore riprova piú tardi".to_string(),
                queue_overload: "\n\nSe il server é sovraccarico, potrebbe volerci un po' di tempo\n*CPU: {:.1}% - RAM: {:.2}%*".to_string(),
                no_sentence_with_text: "Nessuna frase trovata contenente il testo \"{}\"".to_string(),
                replaying_audio: "Riproduzione audio...".to_string(),
                guild_not_found: "Guild non trovata".to_string(),
                must_be_in_voice: "Devi essere connesso a un canale vocale per utilizzare questo comando".to_string(),
                no_speak_permission: "Non ho il permesso di parlare o connettermi in questo canale".to_string(),
                fakeyou_warning: "\n\nWARNING: FakeYou sta ricevendo troppe richieste, audio generato usando la voce di Google".to_string(),
                bot_not_ready: "Il bot non é ancora pronto opppure un altro user sta usando qualche altro comando.\nPer favore riprova piú tardi o utilizza il comando /stop".to_string(),
                initializing_connection: "Per favore riprova piú tardi, Sto inizializzando la connessione...".to_string(),
                invalid_voice: "Voce non valida selezionata.".to_string(),
                wrong_guild: "Questo bot può essere utilizzato solo nel server padre".to_string(),
                disagio: "Disagio.".to_string(),
                user_no_permission: "Non hai i permessi per utilizzare questo comando in questo canale vocale.".to_string(),
                text_too_long: "Il testo é troppo lungo (massimo 200 caratteri). Accorcialo e riprova.".to_string(),
            }
        }
    }
}
