use std::env;

#[derive(Debug)]
pub struct Lang {
    pub join_success: String,
    pub join_success_to_self: String,
    pub join_error: String,
    pub leave_success: String,
    pub not_connected: String,
    pub stop_success: String,
    pub tts_error: String,
    pub tts_error_google: String,
    pub playing: String,
    pub no_sentence: String,
    pub invalid_extension: String,
    pub audio_playback: String,
    pub admin_parent_server: String,
    pub admin_only: String,
    pub restarting: String,
    pub nickname_too_long: String,
    pub nickname_changed: String,
    pub unsupported_file: String,
    pub avatar_changed: String,
    pub spam_messages: Vec<String>,
    pub generating_audio: String,
    pub searching_random: String,
    pub discord_api_error: String,
    pub queue_overload: String,
    pub no_sentence_with_text: String,
    pub replaying_audio: String,
    pub guild_not_found: String,
    pub must_be_in_voice: String,
    pub no_speak_permission: String,
    pub bot_not_ready: String,
    pub initializing_connection: String,
    pub invalid_voice: String,
    pub wrong_guild: String,
    pub disagio: String,
    pub user_no_permission: String,
    pub text_too_long: String,
    pub file_too_large: String,
    pub file_expired: String,
    pub audio_download_failed: String,
    pub image_too_small: String,
    pub processing: String,
    pub ask_generating: String,
    pub ask_error: String,
    pub ask_refused: String,
    pub ask_not_configured: String,
    pub ask_text_too_long: String,
    pub invalid_effect: String,
    pub volume_set: String,
    pub translating: String,
    pub help_title: String,
    pub help_description: String,
    pub help_button_voice: String,
    pub help_button_ai: String,
    pub help_button_admin: String,
    pub help_button_all: String,
    pub joke_error: String,
    pub stats_title: String,
    pub stats_database: String,
    pub stats_cache: String,
    pub stats_uptime: String,
    pub stats_cpu: String,
    pub stats_ram: String,
    pub stats_llm: String,
    pub stats_errors: String,
    pub not_configured: String,
    pub endpoint_label: String,
    // Help descriptions (values shown in the /help category embeds).
    pub help_join_desc: String,
    pub help_leave_desc: String,
    pub help_stop_desc: String,
    pub help_speak_desc: String,
    pub help_random_desc: String,
    pub help_joke_desc: String,
    pub help_volume_desc: String,
    pub help_audio_desc: String,
    pub help_soundboard_desc: String,
    pub help_ask_desc: String,
    pub help_translate_desc: String,
    pub help_stats_desc: String,
    pub help_restart_desc: String,
    pub help_rename_desc: String,
    pub help_avatar_desc: String,
    pub help_help_desc: String,
    pub eavesdrop_enabled: String,
    pub eavesdrop_disabled: String,
    pub eavesdrop_not_ready: String,
    pub eavesdrop_enabled_desc: String,
    pub eavesdrop_disabled_desc: String,
    // Voice cloning
    pub vc_not_configured: String,
    pub vc_usage: String,
    pub vc_too_long: String,
    pub vc_created: String,
    pub vc_exists: String,
    pub vc_invalid_name: String,
    pub vc_sample_invalid: String,
    pub vc_list_title: String,
    pub vc_list_empty: String,
    pub vc_delete_usage: String,
    pub vc_deleted: String,
    pub vc_not_found: String,
    pub vc_owner_mismatch: String,
    pub vc_error: String,
    pub help_createvoice_desc: String,
    pub help_myvoices_desc: String,
    pub help_deletevoice_desc: String,
    // Live recording (/clone, owner only — hidden from autocomplete)
    pub vc_clone_not_owner: String,
    pub vc_clone_usage: String,
    pub vc_clone_no_voice: String,
    pub vc_clone_user_not_in_channel: String,
    pub vc_clone_not_listening: String,
    pub vc_clone_recording: String,
    pub vc_clone_progress: String,
    pub vc_clone_done: String,
    pub vc_clone_no_speech: String,
    pub vc_clone_failed: String,
}

impl Lang {
    pub fn new() -> Self {
        let lang = env::var("LANG").unwrap_or_else(|_| "ita".to_string());
        match lang.as_str() {
            "eng" => Self {
                join_success: "I'm joining the channel".to_string(),
                join_success_to_self: "I'm joining your channel, <@{}>".to_string(),
                join_error: "Error joining the channel".to_string(),
                leave_success: "I'm leaving the channel".to_string(),
                not_connected: "I'm not connected to any channel".to_string(),
                stop_success: "Stopping the bot".to_string(),
                tts_error: "Error generating audio, please try again in a moment.".to_string(),
                tts_error_google: "Error generating audio, try selecting a different voice.".to_string(),
                playing: "Playing: **{}** with voice: {}".to_string(),
                no_sentence: "No sentence found".to_string(),
                invalid_extension: "The file extension is not valid.".to_string(),
                audio_playback: "Done! I'm starting the audio playback!".to_string(),
                admin_parent_server: "Only administrators can use this command in the parent server".to_string(),
                admin_only: "Only administrators can use this command".to_string(),
                restarting: "I'm restarting the bot.".to_string(),
                nickname_too_long: "My nickname cannot be longer than 32 characters".to_string(),
                nickname_changed: "You renamed me to \"{}\"".to_string(),
                unsupported_file: "This file type is not supported".to_string(),
                avatar_changed: "The image has been changed".to_string(),
                spam_messages: vec![
                    "Spam detected. <@{}> I'm watching you.".to_string(),
                    "Spam detected. <@{}> This doesn't make you a good person.".to_string(),
                    "Spam detected. <@{}> I'm stupid but not boring.".to_string(),
                    "Spam detected. <@{}> Take your time.".to_string(),
                    "Spam detected. <@{}> Keep calm.".to_string(),
                    "Spam detected. <@{}> Do you behave like this at home too?".to_string(),
                    "Spam detected. <@{}> Why are you so anxious?".to_string(),
                    "Spam detected. <@{}> I'm adding you to the blacklist.".to_string(),
                ],
                generating_audio: "I'm starting to generate audio for the sentence: **{}**{}".to_string(),
                searching_random: "I'm looking for a random sentence{}".to_string(),
                discord_api_error: "Discord API Error, please try again later".to_string(),
                queue_overload: "\n\nIf the server is overloaded, it might take a while\n*CPU: {:.1}% - RAM: {:.2}%*".to_string(),
                no_sentence_with_text: "No sentence found containing the text \"{}\"".to_string(),
                replaying_audio: "Replaying audio...".to_string(),
                guild_not_found: "Guild not found".to_string(),
                must_be_in_voice: "You must be in a voice channel to use this command".to_string(),
                no_speak_permission: "I don't have permission to speak or connect in this channel".to_string(),
                bot_not_ready: "The bot is not ready yet or another user is using a command.\nPlease try again later or use the /stop command".to_string(),
                initializing_connection: "Please try again later, I'm initializing the connection...".to_string(),
                invalid_voice: "Invalid voice selected.".to_string(),
                wrong_guild: "This bot can only be used in the parent server".to_string(),
                disagio: "Disagio.".to_string(),
                user_no_permission: "You don't have permission to use this command in this voice channel.".to_string(),
                text_too_long: "The text is too long (max 200 characters). Please shorten it and try again.".to_string(),
                file_too_large: "The audio file is too large (max {} MB). Please use a smaller file.".to_string(),
                file_expired: "This audio file has expired. Please generate it again.".to_string(),
                audio_download_failed: "Failed to download the audio file. Please try again.".to_string(),
                image_too_small: "The image is too small. Minimum size is 128x128 pixels.".to_string(),
                processing: "⏳ Processing...".to_string(),
                ask_generating: "🤔 Thinking about: **{}**{}".to_string(),
                ask_error: "The AI is currently unavailable. Please try again later.".to_string(),
                ask_refused: "The AI declined to answer that one 🙈. Try asking something else.".to_string(),
                ask_not_configured: "The AI is not configured. Set LLM_ENDPOINTS and LLM_MODELS to enable this command.".to_string(),
                ask_text_too_long: "The question is too long (max 500 characters). Please shorten it and try again.".to_string(),
                invalid_effect: "Invalid audio effect selected.".to_string(),
                volume_set: "Volume set to {}%".to_string(),
                translating: "🌐 Translating: **{}** to {}{}".to_string(),
                help_title: "🤖 Bot Commands".to_string(),
                help_description: "Click a button below to browse commands by category.".to_string(),
                help_button_voice: "🎵 Voice & Audio".to_string(),
                help_button_ai: "🤖 AI & LLM".to_string(),
                help_button_admin: "🔧 Admin".to_string(),
                help_button_all: "📋 All Commands".to_string(),
                joke_error: "Failed to fetch a joke. Please try again later.".to_string(),
                stats_title: "📊 Bot Statistics".to_string(),
                stats_database: "Database".to_string(),
                stats_cache: "TTS Cache".to_string(),
                stats_uptime: "Uptime".to_string(),
                stats_cpu: "CPU".to_string(),
                stats_ram: "RAM".to_string(),
                stats_llm: "LLM".to_string(),
                stats_errors: "Errors".to_string(),
                not_configured: "Not configured".to_string(),
                endpoint_label: "endpoint(s)".to_string(),
                help_join_desc: "Join the voice channel you're in".to_string(),
                help_leave_desc: "Leave the voice channel".to_string(),
                help_stop_desc: "Stop current audio playback".to_string(),
                help_speak_desc: "Speak text with TTS (Google). Optional: voice, effect".to_string(),
                help_random_desc: "Play a random sentence from the database. Optional: voice, text search, effect".to_string(),
                help_joke_desc: "Fetch a random joke and speak it via TTS. Optional: voice, effect".to_string(),
                help_volume_desc: "Set playback volume (0-100). Default: 100".to_string(),
                help_audio_desc: "Play an uploaded audio file in voice chat".to_string(),
                help_soundboard_desc: "Search MyInstants sounds, browse paginated results and play one".to_string(),
                help_ask_desc: "Ask the AI a question. Uses database sentences as personality. Requires LLM config. Optional: voice, effect".to_string(),
                help_translate_desc: "Translate text to another language via LLM, then speak it. Optional: voice, effect".to_string(),
                help_stats_desc: "Show bot statistics (database, cache, CPU, RAM, uptime)".to_string(),
                help_restart_desc: "Restart the bot (admin only, parent server only)".to_string(),
                help_rename_desc: "Change the bot's nickname (admin only, parent server only)".to_string(),
                help_avatar_desc: "Change the bot's avatar image (admin only, parent server only)".to_string(),
                help_help_desc: "Show this help message".to_string(),
                eavesdrop_enabled: "Voice eavesdropping ENABLED — I may randomly comment on conversations again.".to_string(),
                eavesdrop_disabled: "Voice eavesdropping DISABLED — I will stay quiet until you use /enable.".to_string(),
                eavesdrop_not_ready: "The eavesdrop feature is not initialized yet, please try again later.".to_string(),
                eavesdrop_enabled_desc: "Re-enable random voice eavesdropping".to_string(),
                eavesdrop_disabled_desc: "Silence random voice eavesdropping".to_string(),
                vc_not_configured: "Voice cloning is not available on this server.".to_string(),
                vc_usage: "Usage: /createvoice name:<name> sample:<audio file>".to_string(),
                vc_too_long: "The voice name must be 1-64 characters (A-Z, a-z, 0-9, _ -).".to_string(),
                vc_created: "Voice **{}** created! Use it with /speak --voice {}".to_string(),
                vc_exists: "A voice named **{}** already exists — delete it first with /deletevoice.".to_string(),
                vc_invalid_name: "Invalid voice name: use 1-64 characters from A-Z, a-z, 0-9, _ and - (reserved names are not allowed).".to_string(),
                vc_sample_invalid: "Could not read the audio sample — attach an MP3 or WAV file with 10-30 seconds of clean speech.".to_string(),
                vc_list_title: "🎙️ Cloned voices".to_string(),
                vc_list_empty: "No cloned voices yet — create one with /createvoice.".to_string(),
                vc_delete_usage: "Usage: /deletevoice name:<voice name>".to_string(),
                vc_deleted: "Voice **{}** deleted.".to_string(),
                vc_not_found: "Voice **{}** not found.".to_string(),
                vc_owner_mismatch: "You can only delete your own cloned voices.".to_string(),
                vc_error: "Voice cloning error: {}".to_string(),
                help_createvoice_desc: "Create a cloned voice from an attached audio sample".to_string(),
                help_myvoices_desc: "List all cloned voices".to_string(),
                help_deletevoice_desc: "Delete a previously cloned voice".to_string(),
                vc_clone_not_owner: "Only the server owner can use /clone.".to_string(),
                vc_clone_usage: "Usage: /clone user:<@user> name:<voice_name> — the user must be in my voice channel and speak for {}/{} seconds.".to_string(),
                vc_clone_no_voice: "I'm not connected to any voice channel. Use /join first.".to_string(),
                vc_clone_user_not_in_channel: "That user is not connected to my voice channel — they must be in the same channel as the bot to be recorded.".to_string(),
                vc_clone_not_listening: "Could not start voice capture in this channel.".to_string(),
                vc_clone_recording: "🔴 Recording **{}**... they need to talk now! (target: {}s of speech)".to_string(),
                vc_clone_progress: "Recording... {:.0}s of speech captured so far (target {}s). Keep talking, {}!".to_string(),
                vc_clone_done: "Captured {:.1}s of speech — cloning voice **{}** now...".to_string(),
                vc_clone_no_speech: "No speech detected from that user. They need to actually talk into their microphone while I record.".to_string(),
                vc_clone_failed: "Voice cloning failed: {}".to_string(),
            },
            _ => Self {
                join_success: "Sto entrando nel canale".to_string(),
                join_success_to_self: "Sto entrando nel tuo canale, <@{}>".to_string(),
                join_error: "Errore nell'entrare nel canale".to_string(),
                leave_success: "Sto lasciando il canale".to_string(),
                not_connected: "Non sono connesso a nessun canale".to_string(),
                stop_success: "Interrompo il bot".to_string(),
                tts_error: "Errore nella generazione dell'audio, riprovare fra qualche istante.".to_string(),
                tts_error_google: "Errore nella generazione dell'audio, prova a selezionare una voce diversa.".to_string(),
                playing: "Sto riproducendo: **{}** con voce: {}".to_string(),
                no_sentence: "Nessuna frase trovata".to_string(),
                invalid_extension: "L'estensione del file non è valida.".to_string(),
                audio_playback: "Fatto! Sto avviando la riproduzione dell'audio!".to_string(),
                admin_parent_server: "Solo gli amministratori possono utilizzare questo comando nel server padre".to_string(),
                admin_only: "Solo gli amministratori possono utilizzare questo comando".to_string(),
                restarting: "Sto riavviando il bot.".to_string(),
                nickname_too_long: "Il mio nickname non puó essere piú lungo di 32 caratteri".to_string(),
                nickname_changed: "Mi hai rinominato in \"{}\"".to_string(),
                unsupported_file: "Questo tipo di file non é supportato".to_string(),
                avatar_changed: "L'immagine é stata modificata".to_string(),
                spam_messages: vec![
                    "Spam detected. <@{}> Ti sto guardando.".to_string(),
                    "Spam detected. <@{}> Questo non ti rende una brava persona.".to_string(),
                    "Spam detected. <@{}> Sono stupido ma non noioso.".to_string(),
                    "Spam detected. <@{}> Prenditi il tuo tempo.".to_string(),
                    "Spam detected. <@{}> Mantieni la calma.".to_string(),
                    "Spam detected. <@{}> Anche a casa tua ti comporti cosí?".to_string(),
                    "Spam detected. <@{}> Perché sei cosí ansioso?".to_string(),
                    "Spam detected. <@{}> Ti aggiungo alla blacklist.".to_string(),
                ],
                generating_audio: "Inizio a generare l'audio per la frase: **{}**{}".to_string(),
                searching_random: "Sto cercando una frase casuale{}".to_string(),
                discord_api_error: "Discord API Error, per favore riprova piú tardi".to_string(),
                queue_overload: "\n\nSe il server é sovraccarico, potrebbe volerci un po' di tempo\n*CPU: {:.1}% - RAM: {:.2}%*".to_string(),
                no_sentence_with_text: "Nessuna frase trovata contenente il testo \"{}\"".to_string(),
                replaying_audio: "Riproduzione audio...".to_string(),
                guild_not_found: "Guild non trovata".to_string(),
                must_be_in_voice: "Devi essere connesso a un canale vocale per utilizzare questo comando".to_string(),
                no_speak_permission: "Non ho il permesso di parlare o connettermi in questo canale".to_string(),
                bot_not_ready: "Il bot non é ancora pronto opppure un altro user sta usando qualche altro comando.\nPer favore riprova piú tardi o utilizza il comando /stop".to_string(),
                initializing_connection: "Per favore riprova piú tardi, Sto inizializzando la connessione...".to_string(),
                invalid_voice: "Voce non valida selezionata.".to_string(),
                wrong_guild: "Questo bot può essere utilizzato solo nel server padre".to_string(),
                disagio: "Disagio.".to_string(),
                user_no_permission: "Non hai i permessi per utilizzare questo comando in questo canale vocale.".to_string(),
                text_too_long: "Il testo é troppo lungo (massimo 200 caratteri). Accorcialo e riprova.".to_string(),
                file_too_large: "Il file audio é troppo grande (massimo {} MB). Usa un file piú piccolo.".to_string(),
                file_expired: "Questo file audio é scaduto. Generalo di nuovo.".to_string(),
                audio_download_failed: "Impossibile scaricare il file audio. Riprova.".to_string(),
                image_too_small: "L'immagine é troppo piccola. La dimensione minima é 128x128 pixel.".to_string(),
                processing: "⏳ Elaborazione in corso...".to_string(),
                ask_generating: "🤔 Sto pensando a: **{}**{}".to_string(),
                ask_error: "L'IA non é al momento disponibile. Riprova piú tardi.".to_string(),
                ask_refused: "L'IA ha declinato di rispondere 🙈. Prova a chiedere qualcos'altro.".to_string(),
                ask_not_configured: "L'IA non é configurata. Imposta LLM_ENDPOINTS e LLM_MODELS per abilitare questo comando.".to_string(),
                ask_text_too_long: "La domanda é troppo lunga (massimo 500 caratteri). Accorciala e riprova.".to_string(),
                invalid_effect: "Effetto audio non valido selezionato.".to_string(),
                volume_set: "Volume impostato a {}%".to_string(),
                translating: "🌐 Traduzione di: **{}** in {}{}".to_string(),
                help_title: "🤖 Comandi del Bot".to_string(),
                help_description: "Clicca un pulsante qui sotto per sfogliare i comandi per categoria.".to_string(),
                help_button_voice: "🎵 Voce & Audio".to_string(),
                help_button_ai: "🤖 IA & LLM".to_string(),
                help_button_admin: "🔧 Admin".to_string(),
                help_button_all: "📋 Tutti i Comandi".to_string(),
                joke_error: "Impossibile recuperare una battuta. Riprova piú tardi.".to_string(),
                stats_title: "📊 Statistiche del Bot".to_string(),
                stats_database: "Database".to_string(),
                stats_cache: "Cache TTS".to_string(),
                stats_uptime: "Uptime".to_string(),
                stats_cpu: "CPU".to_string(),
                stats_ram: "RAM".to_string(),
                stats_llm: "LLM".to_string(),
                stats_errors: "Errori".to_string(),
                not_configured: "Non configurato".to_string(),
                endpoint_label: "endpoint".to_string(),
                help_join_desc: "Entra nel canale vocale in cui ti trovi".to_string(),
                help_leave_desc: "Lascia il canale vocale".to_string(),
                help_stop_desc: "Interrompe la riproduzione audio corrente".to_string(),
                help_speak_desc: "Ripeti un testo con TTS (Google). Opzionale: voce, effetto".to_string(),
                help_random_desc: "Riproduce una frase casuale dal database. Opzionale: voce, ricerca testo, effetto".to_string(),
                help_joke_desc: "Recupera una battuta casuale e la pronuncia via TTS. Opzionale: voce, effetto".to_string(),
                help_volume_desc: "Imposta il volume (0-100). Default: 100".to_string(),
                help_audio_desc: "Riproduce un file audio caricato nel canale vocale".to_string(),
                help_soundboard_desc: "Cerca suoni su MyInstants, sfoglia i risultati paginati e riproducili".to_string(),
                help_ask_desc: "Fai una domanda all'AI. Usa le frasi del database come personalità. Richiede configurazione LLM. Opzionale: voce, effetto".to_string(),
                help_translate_desc: "Traduce testo in un'altra lingua via LLM, poi lo pronuncia. Opzionale: voce, effetto".to_string(),
                help_stats_desc: "Mostra le statistiche del bot (database, cache, CPU, RAM, uptime)".to_string(),
                help_restart_desc: "Riavvia il bot (solo admin, solo server padre)".to_string(),
                help_rename_desc: "Cambia il nickname del bot (solo admin, solo server padre)".to_string(),
                help_avatar_desc: "Cambia l'immagine avatar del bot (solo admin, solo server padre)".to_string(),
                help_help_desc: "Mostra questo messaggio di aiuto".to_string(),
                eavesdrop_enabled: "Ascolto casuale ATTIVATO — potrei commentare di nuovo le conversazioni a caso.".to_string(),
                eavesdrop_disabled: "Ascolto casuale DISATTIVATO — starò zitto finché non usi /enable.".to_string(),
                eavesdrop_not_ready: "La funzione di ascolto casuale non è ancora inizializzata, riprova più tardi.".to_string(),
                eavesdrop_enabled_desc: "Riattiva i commenti vocali casuali".to_string(),
                eavesdrop_disabled_desc: "Silenzia i commenti vocali casuali".to_string(),
                vc_not_configured: "La clonazione vocale non è disponibile su questo server.".to_string(),
                vc_usage: "Uso: /createvoice nome:<nome> sample:<file audio>".to_string(),
                vc_too_long: "Il nome della voce deve essere di 1-64 caratteri (A-Z, a-z, 0-9, _ -).".to_string(),
                vc_created: "Voce **{}** creata! Usala con /speak --voice {}".to_string(),
                vc_exists: "Esiste già una voce chiamata **{}** — eliminala prima con /deletevoice.".to_string(),
                vc_invalid_name: "Nome voce non valido: usa 1-64 caratteri tra A-Z, a-z, 0-9, _ e - (i nomi riservati non sono ammessi).".to_string(),
                vc_sample_invalid: "Impossibile leggere il campione audio — allega un file MP3 o WAV con 10-30 secondi di voce pulita.".to_string(),
                vc_list_title: "🎙️ Voci clonate".to_string(),
                vc_list_empty: "Nessuna voce clonata — creane una con /createvoice.".to_string(),
                vc_delete_usage: "Uso: /deletevoice nome:<nome voce>".to_string(),
                vc_deleted: "Voce **{}** eliminata.".to_string(),
                vc_not_found: "Voce **{}** non trovata.".to_string(),
                vc_owner_mismatch: "Puoi eliminare solo le tue voci clonate.".to_string(),
                vc_error: "Errore di clonazione vocale: {}".to_string(),
                help_createvoice_desc: "Crea una voce clonata da un campione audio allegato".to_string(),
                help_myvoices_desc: "Mostra tutte le voci clonate".to_string(),
                help_deletevoice_desc: "Elimina una voce precedentemente clonata".to_string(),
                vc_clone_not_owner: "Solo il proprietario del server può usare /clone.".to_string(),
                vc_clone_usage: "Uso: /clone utente:<@utente> nome:<nome_voce> — l'utente deve essere nel mio canale vocale e parlare per {}/{} secondi.".to_string(),
                vc_clone_no_voice: "Non sono connesso a nessun canale vocale. Usa prima /join.".to_string(),
                vc_clone_user_not_in_channel: "L'utente non è nel mio canale vocale — deve essere nello stesso canale del bot per essere registrato.".to_string(),
                vc_clone_not_listening: "Impossibile avviare la cattura audio in questo canale.".to_string(),
                vc_clone_recording: "🔴 Sto registrando **{}**... ora deve parlare! (obiettivo: {}s di voce)".to_string(),
                vc_clone_progress: "Registrazione... {:.0}s di voce catturati finora (obiettivo {}s). Continua a parlare, {}!".to_string(),
                vc_clone_done: "Catturati {:.1}s di voce — sto clonando la voce **{}**...".to_string(),
                vc_clone_no_speech: "Nessuna voce rilevata da quell'utente. Deve davvero parlare nel microfono mentre registro.".to_string(),
                vc_clone_failed: "Clonazione vocale fallita: {}".to_string(),
            }
        }
    }
}

pub fn config_enabled() -> bool {
    std::env::var("VOICE_EAVESDROP_ENABLED")
        .unwrap_or_else(|_| "false".to_string())
        .to_lowercase() == "true"
}

pub fn config_min_secs() -> u64 {
    std::env::var("VOICE_EAVESDROP_MIN_SECS")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(300)
}

pub fn config_max_secs() -> u64 {
    std::env::var("VOICE_EAVESDROP_MAX_SECS")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(1200)
}
