# Use an official Python runtime as a parent image
FROM python:3.11.8-slim

# Install git
RUN apt-get update && apt-get install -y git \
    build-essential \
    libclblast-dev \
    libopenblas-dev

COPY koboldcpp.git koboldcpp


WORKDIR /koboldcpp


RUN pip install --no-cache-dir --trusted-host pypi.python.org -r requirements.txt
RUN make LLAMA_OPENBLAS=1 LLAMA_CLBLAST=1 LLAMA_PORTABLE=1 -j$(nproc)

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /koboldcpp

CMD ["python", "koboldcpp.py"]