FROM python:3.11-slim-trixie

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        ffmpeg \
        procps \
        gcc

RUN pip3 install -U pip
RUN pip3 install --no-cache --upgrade pip setuptools

COPY requirements-telegram.txt .

RUN pip3 install --default-timeout=900 -r requirements-telegram.txt

WORKDIR /app

COPY telegram-bot.py .
COPY database.py .
COPY entrypoint-telegram.sh .
RUN chmod +x entrypoint-telegram.sh

CMD ["./entrypoint-telegram.sh"]
